"""
PR의 커밋된 Java 파일을 감지하고
Claude가 블로그 글 이안을 PR 코멘트로 작성합니다.
PR 코멘트로 수정 요청 가능, 머지 후 티스토리 자동 포스팅.
"""

import os
import re
import requests
import anthropic
from datetime import datetime

GITHUB_TOKEN = os.environ["ALGO_GITHUB_TOKEN"]
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
GITHUB_REPO = "hyemii/archive-algo"
TISTORY_ACCESS_TOKEN = os.environ.get("TISTORY_ACCESS_TOKEN", "")  # 추후 설정
BLOG_NAME = "archive-log"

GITHUB_API = "https://api.github.com"
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}

client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)


# ──────────────────────────────────────────
# 1. PR 정보 수집
# ──────────────────────────────────────────

def get_open_prs() -> list[dict]:
    """solutions/ 경로의 Java 파일이 포함된 오픈 PR 목록"""
    response = requests.get(
        f"{GITHUB_API}/repos/{GITHUB_REPO}/pulls",
        headers=HEADERS,
        params={"state": "open"}
    )
    return response.json()


def get_pr_java_files(pr_number: int) -> list[dict]:
    """PR에 포함된 Java 파일 목록 + 코드 내용"""
    response = requests.get(
        f"{GITHUB_API}/repos/{GITHUB_REPO}/pulls/{pr_number}/files",
        headers=HEADERS
    )
    files = []
    for f in response.json():
        if f["filename"].startswith("solutions/") and f["filename"].endswith(".java"):
            files.append({
                "filename": f["filename"],
                "raw_url": f["raw_url"]
            })
    return files


def get_file_content(raw_url: str) -> str:
    response = requests.get(raw_url, headers=HEADERS)
    return response.text


def parse_file_info(filepath: str) -> dict:
    """solutions/day01/Day1_1.java → day=1, problem_num=1"""
    match = re.search(r"day(\d+)/Day(\d+)_(\d+)\.java", filepath)
    if not match:
        return {}
    return {
        "day": int(match.group(1)),
        "problem_num": int(match.group(3))
    }


# ──────────────────────────────────────────
# 2. 연관 Issue 찾기
# ──────────────────────────────────────────

def find_issue(day: int, problem_num: int) -> dict:
    response = requests.get(
        f"{GITHUB_API}/repos/{GITHUB_REPO}/issues",
        headers=HEADERS,
        params={"state": "open", "labels": f"Day-{day}", "per_page": 100}
    )
    for issue in response.json():
        if f"Problem {problem_num}" in issue.get("body", "") or \
           f"Problem {problem_num}" in issue.get("title", ""):
            return issue
    return {}


# ──────────────────────────────────────────
# 3. Claude로 블로그 글 이안 생성
# ──────────────────────────────────────────

def generate_blog_draft(code: str, issue: dict) -> str:
    """풀이 코드 + 문제 내용 기반으로 블로그 글 이안 생성"""

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2500,
        messages=[{
            "role": "user",
            "content": f"""
당신은 8년차 Java 백엔드 개발자의 코테 풀이를 리뷰하고 블로그 글을 작성하는 어시스턴트입니다.

아래는 블로그 글 형식 예시입니다 (이 형식을 정확히 따르세요):

---
## 📋 문제 설명
(문제 내용)

## 🟢 입력 조건
(조건들)

## 🔴 출력 조건
(조건들)

## 🧪 예시 입력 / 출력
```
(예시)
```

## ✍️ 직접 구현한 코드 (초기 버전)
```java
(풀이 코드)
```

## ✅ 개선 포인트
(현재 코드의 문제점과 개선 방향 3~5줄)

## ✨ 개선된 코드 (리팩토링 버전)
```java
(리팩토링된 코드)
```

## 💡 정리
| 항목 | 개선 전 | 개선 후 |
|------|---------|---------|
(3~5행)
---

문제 내용 (Issue):
{issue.get("body", "")}

제출한 풀이 코드:
```java
{code}
```

위 형식으로 블로그 글 이안을 작성해주세요.
마지막에 추천 태그도 추가해주세요: **태그**: `tag1`, `tag2`, ...
"""
        }]
    )

    return message.content[0].text


# ──────────────────────────────────────────
# 4. PR 코멘트 등록
# ──────────────────────────────────────────

def post_pr_comment(pr_number: int, body: str):
    response = requests.post(
        f"{GITHUB_API}/repos/{GITHUB_REPO}/issues/{pr_number}/comments",
        headers=HEADERS,
        json={"body": body}
    )
    if response.status_code == 201:
        print(f"✅ PR #{pr_number} 코멘트 등록 완료")
    else:
        print(f"❌ 코멘트 등록 실패: {response.status_code}")


def format_pr_comment(draft: str, day: int, problem_num: int) -> str:
    return f"""## 🤖 블로그 글 이안 - Day {day} Problem {problem_num}

> 아래 이안을 검토해주세요.
> 수정이 필요하면 이 코멘트에 답글로 요청해주세요. (예: "개선 포인트 다시 써줘")
> 최종 확인 후 PR을 머지하면 티스토리에 자동 포스팅됩니다.

---

{draft}

---
*generated by Claude @ {datetime.now().strftime("%Y.%m.%d %H:%M")}*
"""


# ──────────────────────────────────────────
# 5. 머지 후 티스토리 자동 포스팅 (Selenium)
# ──────────────────────────────────────────

def post_to_tistory_if_merged(pr_number: int, draft: str):
    """PR이 머지된 경우 티스토리에 자동 포스팅 (main_v3.py의 Selenium 방식 활용)"""
    response = requests.get(
        f"{GITHUB_API}/repos/{GITHUB_REPO}/pulls/{pr_number}",
        headers=HEADERS
    )
    pr = response.json()

    if pr.get("merged"):
        print(f"✅ PR #{pr_number} 머지 확인 → 티스토리 포스팅 시작")
        # TODO: Selenium 포스팅 연동 (main_v3.py의 post_to_tistory 함수 활용)
        # 현재는 이안 출력만
        print("📄 포스팅할 내용:")
        print(draft[:200] + "...")
    else:
        print(f"ℹ️ PR #{pr_number} 아직 머지되지 않음 → 포스팅 생략")


# ──────────────────────────────────────────
# 6. 메인 실행
# ──────────────────────────────────────────

def run():
    print(f"\n{'='*50}")
    print(f"🚀 PR 리뷰 봇 시작")
    print(f"{'='*50}\n")

    prs = get_open_prs()
    if not prs:
        print("오픈된 PR 없음")
        return

    for pr in prs:
        pr_number = pr["number"]
        print(f"🔍 PR #{pr_number}: {pr['title']}")

        java_files = get_pr_java_files(pr_number)
        if not java_files:
            print("   Java 파일 없음 → 스킵\n")
            continue

        # 이미 Claude 코멘트가 있으면 스킵
        comments_res = requests.get(
            f"{GITHUB_API}/repos/{GITHUB_REPO}/issues/{pr_number}/comments",
            headers=HEADERS
        )
        existing = [c for c in comments_res.json() if "블로그 글 이안" in c.get("body", "")]
        if existing:
            print("   이미 이안 코멘트 있음 → 스킵\n")
            continue

        for file_info in java_files:
            info = parse_file_info(file_info["filename"])
            if not info:
                continue

            day = info["day"]
            problem_num = info["problem_num"]
            print(f"   📝 Day {day} - Problem {problem_num} 처리 중...")

            code = get_file_content(file_info["raw_url"])
            issue = find_issue(day, problem_num)

            if not issue:
                print(f"   ⚠️ 연관 Issue 없음")
                continue

            draft = generate_blog_draft(code, issue)
            comment = format_pr_comment(draft, day, problem_num)
            post_pr_comment(pr_number, comment)

        print()

    print("🎉 완료")


if __name__ == "__main__":
    run()
